version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_game_library
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=game-library

volumes:
  mongo-data:
    driver: local